-- Table des équipes (Métadonnées & Style de jeu)
CREATE TABLE IF NOT EXISTS teams_metadata (
    team_id INT PRIMARY KEY,
    name TEXT,              -- Alias (legacy), préférer nom_equipe
    nom_equipe TEXT,        -- Nom officiel de l'équipe (API / source)
    league_id INT,
    current_archetype TEXT, -- Ex: 'Pace & Space', 'Grit & Grind'
    profile_vector JSONB,   -- Ex: {"pace": 95.5, "def_rtg": 112.0}
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Historique des matchs (passés + calendrier futur)
-- home_score/away_score NULL = match à venir (pas encore joué)
CREATE TABLE IF NOT EXISTS games_history (
    game_id INT PRIMARY KEY,
    date DATE,
    league_id INT,
    season TEXT,
    home_id INT,
    away_id INT,
    home_score INT,  -- NULL si match à venir
    away_score INT   -- NULL si match à venir
);

-- Box Scores (Stats détaillées nettoyées par le Sniffer)
CREATE TABLE IF NOT EXISTS box_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id INT REFERENCES games_history(game_id),
    team_id INT,
    opponent_id INT,
    is_home BOOLEAN,
    date DATE,  -- Redondant (dispo via games_history) pour requêtes rapides
    pace FLOAT,
    off_rtg FLOAT,
    def_rtg FLOAT,
    efg_pct FLOAT,
    orb_pct FLOAT,
    tov_pct FLOAT,
    ft_rate FLOAT,
    three_rate FLOAT, -- Pour détecter le style 'Pace & Space'
    UNIQUE(game_id, team_id)
);
